const SPECIAL_EVENT_EMOJI: Record<string, string> = {
  'Apollo 11 Anniversary': '🚀',
  'April Fools\' Day': '🤡',
  'Arbor Day': '🌳',
  'Ash Wednesday': '✝️',
  'Australia Day': '🇦🇺',
  'Autumn Equinox': '🍂',
  'Bastille Day': '🇫🇷',
  'Black Friday': '🛍️',
  'Black History Month': '✊🏿',
  'Canada Day': '🇨🇦',
  'Christmas Day': '🎄',
  'Christmas Eve': '🎁',
  'Cinco de Mayo': '🇲🇽',
  'Constitution Day': '📜',
  'Cyber Monday': '💻',
  'D-Day Anniversary': '🎖️',
  'Diwali': '🪔',
  'Día de los Muertos': '💀',
  'Earth Day': '🌍',
  'Easter': '🐰',
  'Election Day': '🗳️',
  "Father's Day": '👔',
  'FIFA World Cup 2026 Opens': '⚽',
  'FIFA World Cup Final': '🏆',
  'Flag Day': '🚩',
  'Grandparents Day': '👴',
  'Groundhog Day': '🦫',
  'Halloween': '🎃',
  'Hanukkah': '🕎',
  'Holi': '🎨',
  'Ides of March': '🗡️',
  'Independence Day': '🎆',
  'Indigenous Peoples\' Day': '🪶',
  'International Women\'s Day': '💪',
  'Juneteenth': '✊',
  'Kentucky Derby': '🐎',
  'Kwanzaa Begins': '🕯️',
  'Labor Day': '🛠️',
  'Lincoln\'s Birthday': '🎩',
  'Lunar New Year': '🐉',
  'MLB Opening Day': '⚾',
  'March Madness': '🏀',
  'Mardi Gras': '🎭',
  'Martin Luther King Jr. Day': '🕊️',
  'May Day': '🌷',
  'Memorial Day': '🎗️',
  'Mexican Independence Day': '🌮',
  "Mother's Day": '💐',
  'New Year\'s Day': '🎊',
  'New Year\'s Eve': '🥂',
  'Passover': '🍷',
  'Patriot Day': '🇺🇸',
  'Pearl Harbor Day': '⚓',
  'Pi Day': '🥧',
  'Presidents Day': '🏛️',
  'Shakespeare\'s Birthday': '📖',
  'Small Business Saturday': '🏪',
  'Spring Equinox': '🌸',
  'St. Patrick\'s Day': '☘️',
  'Star Wars Day': '⭐',
  'Talk Like a Pirate Day': '🏴‍☠️',
  'Tax Day': '💰',
  'Thanksgiving': '🦃',
  'Three Kings Day': '👑',
  'United Nations Day': '🌐',
  'Valentine\'s Day': '💝',
  'Veterans Day': '🪖',
  'Winter Solstice': '❄️',
  "Women's Equality Day": '♀️',
  'World Food Day': '🍽️',
};

export function getSpecialEventEmoji(event: string): string {
  return SPECIAL_EVENT_EMOJI[event] ?? '★';
}
